[package]
name = "grid-forge-auth"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
grid-forge-common = { path = "../common" }
grid-forge-domain = { path = "../domain" }
jsonwebtoken.workspace = true
serde.workspace = true
uuid.workspace = true
